apiVersion: acme.com/v1
kind: Workload
metadata:
  name: votes-results-app
  namespace: acme-operators
image: kind-registry:5001/votes-results-app:latest
route: /results
replicas: 1
port: 5174
env: 
  VITE_SERVER_URL: http://localhost
  VITE_SERVER_PORT: "80"
command: ["npm", "run", "dev"]